### ISSUE TITLE
Directory Management 

### ISSUE THREAD

**Issue by Dekablade01** [hoangnhat92/SurveyNimbleChallenge#2]
- Main.storyboard should be removed? 
- ViewControllers, Views, should be organized by screen not type. Imagine you have 1000 ViewControllers, they will be in the same directory.

**Comment by hoangnhat92** [comment]
- I removed Main.storyboard, since I've decided to use SnapKit, we dont need user storyboard anymore
- It create sub folders inside ViewControllers and Views and those sub folders divide by screen type, it was my mistake, because the project only have two controllers, so I dont pay attention to it. But it's really  a good practice in real product. Thanks to pointed out.
